apiVersion: v1
kind: Namespace
metadata:
  name: portfolio
  labels:
    name: portfolio
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: portfolio-sa
  namespace: portfolio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: portfolio
  name: portfolio-role
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: portfolio-rolebinding
  namespace: portfolio
subjects:
- kind: ServiceAccount
  name: portfolio-sa
  namespace: portfolio
roleRef:
  kind: Role
  name: portfolio-role
  apiGroup: rbac.authorization.k8s.io
